#logging:
#  level:
#    io:
#      netty: DEBUG
#      tomcat: DEBUG
#    reactor: DEBUG


logging:
  level:
    com.greglturnquist=DEBUG
    org.springframework.data=TRACE
    reactor.core=TRACE
    reactor.util=TRACE

endpoints:
  health:
    enabled: true
  autoconfig:
    enabled: true
  beans:
    enabled: true
  env:
    enabled: true
  info:
    enabled: true
  mappings:
    enabled: true

resources:
  projectroot: "/Users/i841059/Desktop/reactiveJava"

spring:
  thymeleaf:
    cache: false
    prefix: file:///${resources.projectroot}/src/main/resources/templates/
