logging:
  level:
    io:
      netty: INFO
      tomcat: INFO
    reactor: INFO


resources:
  projectroot: "/Users/i841059/Desktop/reactiveJava"

spring:
  thymeleaf:
    cache: false
    prefix: file:///${resources.projectroot}/src/main/resources/templates/
