logging:
  level:
    io:
      netty: DEBUG
      tomcat: DEBUG
    reactor: DEBUG


endpoints:
  health:
    enabled: true
  autoconfig:
    enabled: true
  beans:
    enabled: true
  env:
    enabled: true
  info:
    enabled: true
  mappings:
    enabled: true

resources:
  projectroot: "/Users/i841059/Desktop/reactiveJava"

spring:
  thymeleaf:
    cache: false
    prefix: file:///${resources.projectroot}/src/main/resources/templates/
